<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-2AKG903" failures="0" tests="6" name="com.Test.Example_9_timeout" time="0.039" errors="1" timestamp="2021-07-09T14:54:04 PDT" skipped="0">
  <testcase classname="com.Test.Example_9_timeout" name="MobileSignOut" time="0.001"/>
  <system-out/>
  <testcase classname="com.Test.Example_9_timeout" name="LoginAPI" time="0.012"/>
  <system-out/>
  <testcase classname="com.Test.Example_9_timeout" name="WebLogin" time="0.004"/>
  <system-out/>
  <testcase classname="com.Test.Example_9_timeout" name="MobileTest" time="0.019">
    <error message="Method com.Test.Example_9_timeout.MobileTest() didn&#039;t finish within the time-out 1" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.Test.Example_9_timeout.MobileTest() didn't finish within the time-out 1
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- MobileTest -->
  <system-out/>
  <testcase classname="com.Test.Example_9_timeout" name="MobileLogin" time="0.002"/>
  <system-out/>
  <testcase classname="com.Test.Example_9_timeout" name="MobileSignIn" time="0.001"/>
  <system-out/>
</testsuite> <!-- com.Test.Example_9_timeout -->
